version: "3.8"

services:
  cobp-backend:
    image: ghcr.io/comparison-of-banking-products/cobp-backend:dev
    container_name: cobp-backend-test
    ports:
      - "8080:8080"
#    depends_on:
#      - ewm-stats-database
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-database:5432/ewm-stats
#      - SPRING_DATASOURCE_USERNAME=dev
#      - SPRING_DATASOURCE_PASSWORD=dev

#  cobp-frontend:
#    image: postgres:15.1-alpine
#    container_name: ewm-main-database
#    ports:
#      - "6542:5432"
#    environment:
#      - POSTGRES_DB=ewm-main
#      - POSTGRES_USER=dev
#      - POSTGRES_PASSWORD=dev
