version: "3.8"

services:
  cobp-database:
    image: postgres:15.5-alpine
    container_name: cobp-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cobp
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  cobp-backend:
    image: ghcr.io/comparison-of-banking-products/cobp-backend:dev
    container_name: cobp-backend
    ports:
      - "8080:8080"
    depends_on:
      - cobp-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cobp-database:5432/cobp
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=dev
      - SPRING_PROFILES_ACTIVE=remote

  cobp-frontend:
    image: ghcr.io/comparison-of-banking-products/cobp-frontend:dev
    container_name: cobp-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cobp-backend
    volumes:
      - ./certbot/:/etc/letsencrypt/:rw
