version: "3.8"

services:
  cobp-database:
    image: postgres:15.5-alpine
    container_name: cobp-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  cobp-backend:
    image: ghcr.io/comparison-of-banking-products/cobp-backend:dev
    container_name: cobp-backend
    ports:
      - "8080:8080"
    depends_on:
      - cobp-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cobp-database:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SPRING_PROFILES_ACTIVE=remote

  cobp-frontend:
    image: ghcr.io/comparison-of-banking-products/cobp-frontend:dev
    container_name: cobp-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cobp-backend
    volumes:
      - ./certbot/:/etc/letsencrypt/:rw

  cobp-support:
    image: ghcr.io/comparison-of-banking-products/cobp-chatbot:dev
    container_name: cobp-support
    ports:
      - "8084:8084"
    depends_on:
      - cobp-backend
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPPORT_GROUP_ID=${SUPPORT_GROUP_ID}
      - SUPPORT_TOPIC_ID=${SUPPORT_TOPIC_ID}
