CREATE TABLE IF NOT EXISTS banks (
  	bic 			BIGINT   		PRIMARY KEY,
	name			VARCHAR(100)    NOT NULL,
	legal_entity 	VARCHAR(100)    NOT NULL,
	description		TEXT            NOT NULL,
	logotype 		VARCHAR(255)    NOT NULL,
	url				VARCHAR(100) 	NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_types (
  	id 						INT          	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	type					VARCHAR(20) 	NOT NULL
);

CREATE TABLE IF NOT EXISTS currencies (
    num					    INT          	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code					VARCHAR(3) 	    NOT NULL,
    currency				VARCHAR(20)   	NOT NULL
 );

CREATE TABLE IF NOT EXISTS credits (
  	id 						BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	banks_bic				BIGINT 			NOT NULL REFERENCES banks(bic),
	name					VARCHAR(100) 	NOT NULL,
	is_active				BOOLEAN			NOT NULL,
	currencies_num  		INT				NOT NULL REFERENCES currencies(num),
	product_url				VARCHAR(100) 	NOT NULL,
	min_amount 		    	INT             NOT NULL,
    max_amount 		    	INT             NOT NULL,
	min_rate				FLOAT           NOT NULL,	
	min_period				INT             NOT NULL,
	max_period 				INT				NOT NULL,
	payment_type_id			INT             NOT NULL REFERENCES payment_types(id),
	deposit_is_required		BOOLEAN			NOT NULL,
	online_approve			BOOLEAN			NOT NULL,
	online_getting			BOOLEAN			NOT NULL,
	insurance 				BOOLEAN			NOT NULL
);

CREATE TABLE IF NOT EXISTS deposits (
  	id 						BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	banks_bic				BIGINT 			NOT NULL REFERENCES banks(bic),
	name					VARCHAR(100) 	NOT NULL,
	product_url				VARCHAR(255) 	NOT NULL,	
	is_active				BOOLEAN			NOT NULL,
	currencies_num  		INT				NOT NULL REFERENCES currencies(num),
	min_amount 			    INT             NOT NULL,
    max_amount 			    INT				NOT NULL,
	min_rate				FLOAT           NOT NULL,	
	max_rate				FLOAT           NOT NULL,	
	min_period				INT             NOT NULL,
	max_period 				INT             NOT NULL,
	interest_payment		BOOLEAN			NOT NULL,
	capitalization			BOOLEAN         NOT NULL,
	partial_withdrawal		BOOLEAN         NOT NULL,
	replenishment			BOOLEAN         NOT NULL
);

CREATE TABLE IF NOT EXISTS deposit_rates (
  	id 					BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	deposits_id			BIGINT 			NOT NULL REFERENCES deposits(id),
	rate				FLOAT           NOT NULL,
	min_amount 		    INT             NOT NULL,
	max_amount 		    INT				NOT NULL,
	min_period			INT             NOT NULL,
	max_period			INT
)
