DROP TABLE IF EXISTS banks CASCADE;
DROP TABLE IF EXISTS currencies CASCADE;
DROP TABLE IF EXISTS deposit_rates CASCADE;
DROP TABLE IF EXISTS deposits CASCADE;
DROP TABLE IF EXISTS payment_types CASCADE;
DROP TABLE IF EXISTS credits CASCADE;

CREATE TABLE banks (
	bic             INTEGER         NOT NULL,
	name            VARCHAR(100)    NOT NULL,
	legal_entity    VARCHAR(100)    NOT NULL,
	description     TEXT            NOT NULL,
	logo            VARCHAR(100)    NOT NULL,
	url             VARCHAR(100)    NOT NULL,

	CONSTRAINT pk_banks PRIMARY KEY (bic),
	CONSTRAINT uq_banks__name UNIQUE (name),
	CONSTRAINT uq_banks__legal_entity UNIQUE (legal_entity)
);

CREATE TABLE currencies (
	num         INTEGER         NOT NULL,
	code        VARCHAR(3)      NOT NULL,
	currency    VARCHAR(30)     NOT NULL,

	CONSTRAINT pk_currencies PRIMARY KEY (num),
	CONSTRAINT uq_currencies__code UNIQUE (code),
	CONSTRAINT uq_currencies__currency UNIQUE (currency)
);

CREATE TABLE deposits (
	id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
	banks_bic           INTEGER         NOT NULL,
	name                VARCHAR(100)    NOT NULL,
	product_url         VARCHAR(250)    NOT NULL,
	is_active           BOOLEAN         NOT NULL,
	currencies_num      INTEGER         NOT NULL,
	amount_min          INTEGER         NOT NULL,
	amount_max          INTEGER         NOT NULL,
	rate_min            DECIMAL(4,2)    NOT NULL,
	rate_max            DECIMAL(4,2)    NOT NULL,
	term_min            INTEGER         NOT NULL,
	term_max            INTEGER,
	capitalization      BOOLEAN         NOT NULL,
	interest_payment    BOOLEAN         NOT NULL,
	partial_withdrawal  BOOLEAN         NOT NULL,
	replenishment       BOOLEAN         NOT NULL,

	CONSTRAINT pk_deposits PRIMARY KEY (id),
	CONSTRAINT fk_deposits__banks FOREIGN KEY (banks_bic) REFERENCES banks(bic) ON DELETE CASCADE,
	CONSTRAINT fk_deposits__currencies FOREIGN KEY (currencies_num) REFERENCES currencies(num) ON DELETE CASCADE
);

CREATE TABLE deposit_rates (
	id              BIGINT          GENERATED BY DEFAULT AS IDENTITY,
	deposits_id     BIGINT          NOT NULL,
	rate            DECIMAL(4,2)    NOT NULL,
	amount_min      INTEGER         NOT NULL,
	amount_max      INTEGER         NOT NULL,
	term_min        INTEGER         NOT NULL,
	term_max        INTEGER,

	CONSTRAINT pk_deposit_rates PRIMARY KEY (id),
	CONSTRAINT fk_deposit_rates__deposits FOREIGN KEY (deposits_id) REFERENCES deposits(id) ON DELETE CASCADE
);

CREATE TABLE payment_types (
	id      BIGINT          GENERATED BY DEFAULT AS IDENTITY,
	type    VARCHAR(20)     NOT NULL,

	CONSTRAINT pk_payment_types PRIMARY KEY (id),
	CONSTRAINT uq_payment_types__type UNIQUE (type)
);

CREATE TABLE credits (
	id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY,
	banks_bic           INTEGER         NOT NULL,
	name                VARCHAR(100)    NOT NULL,
	product_url         VARCHAR(250)    NOT NULL,
	is_active           BOOLEAN         NOT NULL,
	currencies_num      INTEGER         NOT NULL,
	amount_min          INTEGER         NOT NULL,
	amount_max          INTEGER         NOT NULL,
	rate_min            DECIMAL(4,2)    NOT NULL,
	term_min            INTEGER         NOT NULL,
	term_max            INTEGER         NOT NULL,
	payment_type_id     BIGINT          NOT NULL,
	deposit_is_required BOOLEAN         NOT NULL,
	online_approve      BOOLEAN         NOT NULL,
	online_getting      BOOLEAN         NOT NULL,
	insurance           BOOLEAN         NOT NULL,

	CONSTRAINT pk_credits PRIMARY KEY (id),
	CONSTRAINT fk_credits__banks FOREIGN KEY (banks_bic) REFERENCES banks(bic) ON DELETE CASCADE,
	CONSTRAINT fk_credits__currencies FOREIGN KEY (currencies_num) REFERENCES currencies(num) ON DELETE CASCADE,
	CONSTRAINT fk_credits__payment_types FOREIGN KEY (payment_type_id) REFERENCES payment_types(id) ON DELETE CASCADE
);
