name: Dev test on pull request

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Run 'cobp' Backend App
        run: |
          cd target
          java -jar cobp-backend-0.0.1-SNAPSHOT.jar &

      - uses: matt-ball/newman-action@master
        with:
          collection: ./postman/cobp-backend-api-test.json
