name: SCP and deploy Docker compose manually

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  GITHUB_ACTOR: ${{ github.actor }}
  PAT_PACKAGES: ${{ secrets.PAT_PACKAGES }}
  COBP_DIR: ${{ secrets.COBP_DIR }}
  COMPOSE_CONFIG: docker-compose-remote.yml

jobs:
  scp-and-deploy-compose:
    name: SCP and deploy Docker compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SCP Docker compose config using SSH_KEY to remote
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          source: ${{ env.COMPOSE_CONFIG }}
          target: ${{ secrets.COBP_DIR }}

      - name: SSH execute Docker compose using SSH_KEY on remote
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          envs: REGISTRY, GITHUB_ACTOR, PAT_PACKAGES, COBP_DIR, COMPOSE_CONFIG
          script: |
            cd $COBP_DIR
            echo "$PAT_PACKAGES" | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
            docker compose -f $COMPOSE_CONFIG pull
            docker compose -f $COMPOSE_CONFIG up -d
