name: SCP file to DEV on pull request

on:
  pull_request:
    branches: [ dev ]

jobs:
  scp-to-remote:
    name: SCP file to remote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SCP docker-compose-remote.yml using SSH_KEY to remote
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          source: docker-compose-remote.yml
          target: ${{ secrets.COBP_DIR }}

      - name: SSH execute docker-compose using SSH_KEY on remote
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            cd {{ secrets.COBP_DIR }}
            docker compose pull
            docker compose up -d
